name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to AWS ECR
    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1

    # Build and push Docker image
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: 600627364901.dkr.ecr.ca-central-1.amazonaws.com
        ECR_REPOSITORY: pal-ecr
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Create ECS service if not exists
    - name: Create ECS service if not exists
      run: |
        # Check if the service exists
        SERVICE_EXISTS=$(aws ecs describe-services --cluster pal-cluster --services pal-final-service --region ca-central-1 --query 'services[0].status' --output text 2>/dev/null || echo "NOT_FOUND")
        if [ "$SERVICE_EXISTS" != "ACTIVE" ]; then
          echo "Service pal-final-service does not exist, creating it..."
          aws ecs create-service \
            --cluster pal-cluster \
            --service-name pal-final-service \
            --task-definition inft1210-task \
            --desired-count 2 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-0f04897d52d6a6d4a,subnet-0b9e3010f2d3107f6],securityGroups=[sg-0df550e0dd4956cfc],assignPublicIp=DISABLED}" \
            --load-balancers "targetGroupArn=arn:aws:elasticloadbalancing:ca-central-1:600627364901:targetgroup/pal-fi-PalAL-8WD9X25CIEPT/f5cd3fd34d0da9d0,containerName=pal-container,containerPort=5000" \
            --region ca-central-1
        else
          echo "Service pal-final-service already exists, proceeding with deployment..."
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1

    # Deploy to ECS
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: task-definition.json
        service: pal-final-service
        cluster: pal-cluster
        wait-for-service-stability: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1
